### ISSUE TITLE
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by smallworld-network-wupeng** [anhttran/extreme_3d_faces#28]
root@74a4066c1b48:/app/demoCode# python testBatchModel.py /shared/img_list.txt /shared/3d_output/
> Prepare image /shared/cute_boy.jpg:
>     Number of faces detected: 1
> CNN Model loaded to regress 3D Shape and Texture!
> Loaded the Basel Face Model to write the 3D output!
> Processing image: /shared/3d_output/imgs/cute_boy.png
Traceback (most recent call last):
  File "testBatchModel.py", line 168, in <module>
    features = net(im).data.cpu().numpy()
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "../CNN/shape_model.py", line 239, in forward
    conv1           = self.conv1(conv1_pad)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 282, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 90, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

I have two 2080 card and ubuntu 16.04 but these is a error CUDNN_STATUS_EXECUTION_FAILED when I run program in Dock. I need help

**Comment by smallworld-network-wupeng** [comment]
It is looks torch 0.3.1 unsupported the 2070 card. But when I update torch to 1.0 the model unsupported torch 1.0 .

**Comment by spiketg** [comment]
having the same error with the same card in Ubuntu 18.04

**Comment by digbose92** [comment]
@smallworld-network-wupeng and @spiketg any updates on this issue ?

**Comment by anhttran** [comment]
Dear,
One simple solution is to disable cudnn in the main code:
`torch.backends.cudnn.enabled = False`
Hope it help.
Best regards,
Anh

**Comment by Frank-Dz** [comment]
Same problem.

**Comment by Frank-Dz** [comment]
With docker image installed, I met this error.

ENVs:
- CUDA 10.2
- RTX 2080
- Ubuntu16
- Driver Version: 440.33.01

**Comment by Frank-Dz** [comment]
> It is looks torch 0.3.1 unsupported the 2070 card. But when I update torch to 1.0 the model unsupported torch 1.0 .

Did you solve this?
