### ISSUE TITLE
BaselFaceModel.mat not found

### ISSUE THREAD

**Issue by spiketg** [anhttran/extreme_3d_faces#33]
When running the code I receive the following error. I used docker to install on ubuntu 18.04 and have put the required basel file (01_moprhableModel.mat) in the 3DMM dir but receive this error. 

> CNN Model loaded to regress 3D Shape and Texture!
Traceback (most recent call last):
  File "testBatchModel.py", line 148, in <module>
    model = scipy.io.loadmat(BFM_path,squeeze_me=True,struct_as_record=False)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 207, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 62, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
  File "/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 37, in _open_file
    return open(file_like, 'rb'), True
IOError: [Errno 2] No such file or directory: '../3DMM_model/BaselFaceModel_mod.mat'

**Comment by spiketg** [comment]
missed the instruction sorry
