### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by jtou100** [anhttran/extreme_3d_faces#4]
Today,I run the script jush like:/demoCode# python testBatchModel.py /home/hero/infile.txt /root/rsx,and I met a problem:
> Prepare image /home/hero/xiaoluo.jpg:
>     Number of faces detected: 1
Skipping 
 file path too short
> CNN Model loaded to regress 3D Shape and Texture!
('> Processing image: ', '/root/rsx/imgs/xiaoluo.png', ' ', 'xiaoluo.png', ' ', '1/1')
Regress bump maps
Traceback (most recent call last):
  File "testBatchModel.py", line 183, in <module>
    bumpMapRegressor.estimateBump(bumpModel_path, data_out + "/imList.txt", data_out + "/bump/")
  File "/root/faces/extreme_3d_faces/demoCode/bumpMapRegressor.py", line 332, in estimateBump
    net.cuda()
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 152, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 216, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python2.7/dist-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 453, in _lazy_new
    _lazy_init()
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 152, in _lazy_init
    _check_driver()
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py", line 74, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

I don't kown how to resolve it, Besides,I changed testBatchModel.py,
# load net
try:
        caffe.set_mode_cpu()
        #caffe.set_mode_gpu()
        #caffe.set_device(GPU_ID)
        pass
except Exception as ex:
        print('> Could not setup Caffe in GPU ' +str(GPU_ID) + ' - Error: ' + ex)
        print('> Reverting into CPU mode')
        caffe.set_mode_cpu()
## Opening mean average image

Could you help me?

**Comment by RobertWu-TIBCO** [comment]
I get the same error as I hope to run it without GPU or Nvidia Driver.

I check the error msgs and changed _check_driver function to return 1 at first(vi +55 "/usr/local/lib/python2.7/dist-packages/torch/cuda/__init__.py")

then I changed _cuda_deserialize function to return obj in "/usr/local/lib/python2.7/dist-packages/torch/serialization.py".

now I get the error { AttributeError: 'module' object has no attribute '_cuda_init' } with below error details :
{
 File "/home/pythonhack/extreme_3d_faces-master/demoCode/bumpMapRegressor.py", line 334, in estimateBump
    net.save_images()
  File "/home/pythonhack/extreme_3d_faces-master/demoCode/bumpMapRegressor.py", line 320, in save_images
    images = Variable(images.cuda())
}

I am trying on to see if there is a way to use this project without GPU or Nvidia driver.

Hope the project owner could give a hand on running without GPU.

**Comment by hereitag** [comment]
you should install a pytorch with CUDA.
